"""add cloud account timezones

Revision ID: 00d66ca4fca7
Revises: 41a5c5ca2eac
Create Date: 2026-07-23 15:33:24.693947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d66ca4fca7'
down_revision: Union[str, None] = '41a5c5ca2eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_account_timezones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cloud_provider_account_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('availability_zone', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloud_provider_account_id'], ['cloud_provider_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cloud_provider_account_id', 'region', 'timezone', name='uq_cloud_account_timezone_region_tz')
    )
    op.create_index(op.f('ix_cloud_account_timezones_cloud_provider_account_id'), 'cloud_account_timezones', ['cloud_provider_account_id'], unique=False)
    op.add_column('deployments', sa.Column('cloud_account_timezone_id', sa.Integer(), nullable=True, comment="Optional link to one of the linked cloud account's configured (region, timezone) entries (Phase 22) - lets monitoring/alerts/notifications for this deployment display local time alongside UTC. Nullable and unset by default: existing deployments behave exactly as before (UTC-only) until a user opts one into a configured timezone."))
    op.create_index(op.f('ix_deployments_cloud_account_timezone_id'), 'deployments', ['cloud_account_timezone_id'], unique=False)
    op.create_foreign_key(None, 'deployments', 'cloud_account_timezones', ['cloud_account_timezone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_index(op.f('ix_deployments_cloud_account_timezone_id'), table_name='deployments')
    op.drop_column('deployments', 'cloud_account_timezone_id')
    op.drop_index(op.f('ix_cloud_account_timezones_cloud_provider_account_id'), table_name='cloud_account_timezones')
    op.drop_table('cloud_account_timezones')
    # ### end Alembic commands ###
