"""add cloud sync fields to deployments

Revision ID: 093355726a4c
Revises: c1e61737c503
Create Date: 2026-07-18 19:24:54.566592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093355726a4c'
down_revision: Union[str, None] = 'c1e61737c503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('cloud_provider_account_id', sa.Integer(), nullable=True, comment="If set, this deployment's resource usage can be synced from real cloud provider telemetry using this account's credentials (Phase 12) - see app/services/cloud_sync_service.py."))
    op.add_column('deployments', sa.Column('cloud_resource_identifier', sa.String(length=200), nullable=True, comment='The provider-specific resource this deployment maps to, e.g. an AWS EC2 instance ID - required alongside cloud_provider_account_id for cloud metric syncing to be possible.'))
    op.create_index(op.f('ix_deployments_cloud_provider_account_id'), 'deployments', ['cloud_provider_account_id'], unique=False)
    op.create_foreign_key(None, 'deployments', 'cloud_provider_accounts', ['cloud_provider_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deployments', type_='foreignkey')
    op.drop_index(op.f('ix_deployments_cloud_provider_account_id'), table_name='deployments')
    op.drop_column('deployments', 'cloud_resource_identifier')
    op.drop_column('deployments', 'cloud_provider_account_id')
    # ### end Alembic commands ###
