"""phase23_alert_user_id

Revision ID: 3eca2a257121
Revises: b08de8ac6a0f
Create Date: 2026-07-24 23:49:30.076754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eca2a257121'
down_revision: Union[str, None] = 'b08de8ac6a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'users', ['user_id'], ['id'], referent_schema='cloud_ai_auth', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_column('alerts', 'user_id')
    # ### end Alembic commands ###
