"""add disk/network/cost alerting fields

Revision ID: 41a5c5ca2eac
Revises: 99e3ad159808
Create Date: 2026-07-23 14:29:34.330301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a5c5ca2eac'
down_revision: Union[str, None] = '99e3ad159808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alerts_project_id'), 'alerts', ['project_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('cloud_account_alert_thresholds', sa.Column('disk_warning_threshold', sa.Float(), nullable=True))
    op.add_column('cloud_account_alert_thresholds', sa.Column('disk_critical_threshold', sa.Float(), nullable=True))
    op.add_column('cloud_account_alert_thresholds', sa.Column('disk_saturated_threshold', sa.Float(), nullable=True))
    op.add_column('cloud_account_alert_thresholds', sa.Column('network_warning_threshold', sa.Float(), nullable=True))
    op.add_column('cloud_account_alert_thresholds', sa.Column('network_critical_threshold', sa.Float(), nullable=True))
    op.add_column('cloud_account_alert_thresholds', sa.Column('network_saturated_threshold', sa.Float(), nullable=True))
    op.add_column('deployments', sa.Column('disk_limit_mb', sa.Float(), nullable=True, comment='Configured disk limit per pod, in MB (Phase 21). Nullable - disk-based alerting is skipped for deployments without one configured, the same guard memory_limit_mb already uses.'))
    op.add_column('deployments', sa.Column('network_limit_kbps', sa.Float(), nullable=True, comment='Configured combined (in+out) network bandwidth limit per pod, in kbps (Phase 21). Nullable - network-based alerting is skipped for deployments without one configured.'))
    op.add_column('projects', sa.Column('monthly_budget', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('cost_warning_threshold', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('cost_critical_threshold', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('cost_saturated_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'cost_saturated_threshold')
    op.drop_column('projects', 'cost_critical_threshold')
    op.drop_column('projects', 'cost_warning_threshold')
    op.drop_column('projects', 'monthly_budget')
    op.drop_column('deployments', 'network_limit_kbps')
    op.drop_column('deployments', 'disk_limit_mb')
    op.drop_column('cloud_account_alert_thresholds', 'network_saturated_threshold')
    op.drop_column('cloud_account_alert_thresholds', 'network_critical_threshold')
    op.drop_column('cloud_account_alert_thresholds', 'network_warning_threshold')
    op.drop_column('cloud_account_alert_thresholds', 'disk_saturated_threshold')
    op.drop_column('cloud_account_alert_thresholds', 'disk_critical_threshold')
    op.drop_column('cloud_account_alert_thresholds', 'disk_warning_threshold')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_project_id'), table_name='alerts')
    op.drop_column('alerts', 'project_id')
    # ### end Alembic commands ###
