"""phase24_user_signup_fields_and_email_verification

Revision ID: 734043a1ade2
Revises: 3eca2a257121
Create Date: 2026-07-27 17:31:10.825439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734043a1ade2'
down_revision: Union[str, None] = '3eca2a257121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=60), nullable=True), schema='cloud_ai_auth')
    op.add_column('users', sa.Column('last_name', sa.String(length=60), nullable=True), schema='cloud_ai_auth')
    op.add_column('users', sa.Column('company_name', sa.String(length=150), nullable=True), schema='cloud_ai_auth')
    op.add_column('users', sa.Column('country', sa.String(length=60), nullable=True), schema='cloud_ai_auth')
    # server_default='1' backfills every existing (pre-Phase-24) user as
    # already-verified, so nobody currently using the platform is locked
    # out of login by this change - only new registrations start
    # unverified (the ORM's own Python-side default=False applies then).
    op.add_column(
        'users',
        sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.text('1')),
        schema='cloud_ai_auth',
    )
    op.add_column('users', sa.Column('email_verification_token_hash', sa.String(length=64), nullable=True), schema='cloud_ai_auth')
    op.add_column('users', sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True), schema='cloud_ai_auth')
    op.add_column('users', sa.Column('password_reset_token_hash', sa.String(length=64), nullable=True), schema='cloud_ai_auth')
    op.add_column('users', sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True), schema='cloud_ai_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_expires_at', schema='cloud_ai_auth')
    op.drop_column('users', 'password_reset_token_hash', schema='cloud_ai_auth')
    op.drop_column('users', 'email_verification_expires_at', schema='cloud_ai_auth')
    op.drop_column('users', 'email_verification_token_hash', schema='cloud_ai_auth')
    op.drop_column('users', 'email_verified', schema='cloud_ai_auth')
    op.drop_column('users', 'country', schema='cloud_ai_auth')
    op.drop_column('users', 'company_name', schema='cloud_ai_auth')
    op.drop_column('users', 'last_name', schema='cloud_ai_auth')
    op.drop_column('users', 'first_name', schema='cloud_ai_auth')
    # ### end Alembic commands ###
