"""add cloud_account_alert_thresholds table

Revision ID: 99e3ad159808
Revises: 04ec0076aed1
Create Date: 2026-07-23 13:53:51.255914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e3ad159808'
down_revision: Union[str, None] = '04ec0076aed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_account_alert_thresholds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cloud_provider_account_id', sa.Integer(), nullable=False),
    sa.Column('cpu_warning_threshold', sa.Float(), nullable=True),
    sa.Column('cpu_critical_threshold', sa.Float(), nullable=True),
    sa.Column('cpu_saturated_threshold', sa.Float(), nullable=True),
    sa.Column('memory_warning_threshold', sa.Float(), nullable=True),
    sa.Column('memory_critical_threshold', sa.Float(), nullable=True),
    sa.Column('memory_saturated_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloud_provider_account_id'], ['cloud_provider_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_account_alert_thresholds_cloud_provider_account_id'), 'cloud_account_alert_thresholds', ['cloud_provider_account_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_account_alert_thresholds_cloud_provider_account_id'), table_name='cloud_account_alert_thresholds')
    op.drop_table('cloud_account_alert_thresholds')
    # ### end Alembic commands ###
