"""phase23_notification_contact_and_threshold_fields

Revision ID: b08de8ac6a0f
Revises: 00d66ca4fca7
Create Date: 2026-07-24 19:15:28.537393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08de8ac6a0f'
down_revision: Union[str, None] = '00d66ca4fca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_account_alert_thresholds', sa.Column('cloud_usage_warning_threshold', sa.Float(), nullable=True))
    op.add_column('cloud_account_alert_thresholds', sa.Column('cloud_usage_critical_threshold', sa.Float(), nullable=True))
    op.add_column('cloud_account_alert_thresholds', sa.Column('cloud_usage_saturated_threshold', sa.Float(), nullable=True))
    op.add_column('cloud_account_alert_thresholds', sa.Column('pod_restart_warning_threshold', sa.Float(), nullable=True))
    op.add_column('cloud_account_alert_thresholds', sa.Column('pod_restart_critical_threshold', sa.Float(), nullable=True))
    op.add_column('cloud_account_alert_thresholds', sa.Column('pod_restart_saturated_threshold', sa.Float(), nullable=True))
    op.add_column('notification_settings', sa.Column('secondary_email', sa.String(length=120), nullable=True))
    op.add_column('notification_settings', sa.Column('country_code', sa.String(length=6), nullable=True))
    op.add_column('notification_settings', sa.Column('telegram_username', sa.String(length=100), nullable=True))
    op.add_column(
        'notification_settings',
        sa.Column('notification_language', sa.String(length=10), nullable=False, server_default='en'),
    )
    op.add_column('notification_settings', sa.Column('alert_preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_settings', 'alert_preferences')
    op.drop_column('notification_settings', 'notification_language')
    op.drop_column('notification_settings', 'telegram_username')
    op.drop_column('notification_settings', 'country_code')
    op.drop_column('notification_settings', 'secondary_email')
    op.drop_column('cloud_account_alert_thresholds', 'pod_restart_saturated_threshold')
    op.drop_column('cloud_account_alert_thresholds', 'pod_restart_critical_threshold')
    op.drop_column('cloud_account_alert_thresholds', 'pod_restart_warning_threshold')
    op.drop_column('cloud_account_alert_thresholds', 'cloud_usage_saturated_threshold')
    op.drop_column('cloud_account_alert_thresholds', 'cloud_usage_critical_threshold')
    op.drop_column('cloud_account_alert_thresholds', 'cloud_usage_warning_threshold')
    # ### end Alembic commands ###
