"""add memory_limit_mb to deployments

Revision ID: bec2b8752234
Revises: 59b011f59240
Create Date: 2026-07-15 20:57:53.262818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec2b8752234'
down_revision: Union[str, None] = '59b011f59240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('memory_limit_mb', sa.Float(), nullable=True, comment="Configured memory limit per pod, in MB. Nullable - memory-based optimization recommendations (Phase 6) are skipped for deployments without one configured, since memory_usage_mb alone can't be turned into a utilization percentage without a limit to divide by."))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'memory_limit_mb')
    # ### end Alembic commands ###
