"""add cloud provider accounts

Revision ID: c1e61737c503
Revises: bec2b8752234
Create Date: 2026-07-18 18:28:57.821501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e61737c503'
down_revision: Union[str, None] = 'bec2b8752234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_provider_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('account_identifier', sa.String(length=100), nullable=True),
    sa.Column('credentials_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_name', name='uq_cloud_account_user_name')
    )
    op.create_index(op.f('ix_cloud_provider_accounts_provider'), 'cloud_provider_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_cloud_provider_accounts_user_id'), 'cloud_provider_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cloud_provider_accounts_user_id'), table_name='cloud_provider_accounts')
    op.drop_index(op.f('ix_cloud_provider_accounts_provider'), table_name='cloud_provider_accounts')
    op.drop_table('cloud_provider_accounts')
    # ### end Alembic commands ###
